export type RequestSlipProps = {
  author?: string;
  title?: string;
  location?: string;
  callNumber?: string | undefined;
  catalog: string;
  publisher?: string;
  box?: string;
  folder?: string;
  ms?: string;
  date?: string;
  notes?: string;
  itemInfo?: string[] | never[] | undefined;
  highlightedItemIndex?: number;
  patronName?: string;
  patronAffiliation?: string;
  patronStatus?: string;
  userName?: string;
  userEmail?: string;
  userAffiliation?: string;
  userStatus?: string;
  personPrinting?: string;
  projectName?: string;
  purpose: string | undefined;
  displayPrintButton?: boolean;
};
