import type { RequestSlipProps } from '@/types/RequestSlipProps';
import type { EntryWithItems } from '@/types/EntryWithItems';
import { ProjectWithUserAndBib } from '@/types/ProjectWithUserAndBib';

export default function generateRequestSlipItems(
  entries: EntryWithItems[],
  project: ProjectWithUserAndBib,
  user: any // usually generated by the checkUser lib function
): RequestSlipProps[] {
  // return one slip per item (or one per bib if there are no items)
  //   console.log('***** number of items: ', entries[0].items.length);

  const items: RequestSlipProps[] = entries.flatMap((entry) => {
    const locationArr: string[] = [];
    let locationStr: string;
    // Build item info strings for all items
    const itemInfos =
      entry.items?.map((item) => {
        let info: string = '';
        // console.log('****** item info:', JSON.stringify(item));
        // console.log('****** entry loc: ', entry.location_codes);
        locationArr.push(`${item.location_name} (${item.location_code})`);
        // only add to item info if there's any item-specific info
        if (
          (item.copy_id && parseInt(item.copy_id) > 1) ||
          (item.description && item.description.length > 0) ||
          item.location_code != entry.location_codes
        ) {
          if (
            item.location_code &&
            entry.location_codes &&
            entry.location_codes.length > 1
          ) {
            info += `${item.location_name} (${item.location_code}) `;
          }
          if (item.call_number !== entry.callNumber) {
            info += `${item.call_number} `;
          }
          if (item.description) {
            info += item.description;
          }
          if (item.copy_id && parseInt(item.copy_id) > 1) {
            info += ` c.${item.copy_id}`;
          }
        }
        return info.trim();
      }) ?? [];

    if (itemInfos.length > 0) {
      // One object per item, highlighting the index
      locationStr = [...new Set(locationArr)].join(', ');
      return itemInfos.map((_, idx) => ({
        author: entry.author,
        title: entry.itemTitle,
        callNumber: entry.callNumber ?? undefined,
        notes: entry.notes ?? undefined,
        date: entry.pub_date ?? undefined,
        location: locationStr,
        ms: entry.items[0].ms ?? undefined,
        box: entry.items[0].box ?? undefined,
        folder: entry.items[0].folder ?? undefined,
        itemInfo: itemInfos, // full array of all items
        highlightedItemIndex: idx, // which one is current
        userName: project?.user.name,
        userEmail: project?.user.email,
        userAffiliation: project?.user.affiliation ?? undefined,
        userStatus: project?.user.status ?? undefined,
        personPrinting: user?.name ?? 'Unknown',
        projectName: project?.title,
        purpose: project?.purpose,
      }));
    } else {
      // Fallback: no items, return a single object
      return [
        {
          author: entry.author,
          title: entry.itemTitle,
          callNumber: entry.callNumber ?? undefined,
          notes: entry.notes ?? undefined,
          date: entry.pub_date ?? undefined,
          location: `${entry.location_display} (${entry.location_codes})`,
          box: '',
          folder: '',
          ms: '',
          itemInfo: [],
          highlightedItemIndex: 0,
          userName: project?.user.name,
          userEmail: project?.user.email,
          userAffiliation: project?.user.affiliation ?? undefined,
          userStatus: project?.user.status ?? undefined,
          personPrinting: user?.name ?? 'Unknown',
          projectName: project?.title,
          purpose: project?.purpose,
        },
      ];
    }
  });
  return items;
}
