import { Roboto } from 'next/font/google';
import '@/app/styles/custom-bootstrap.scss';
import styles from './print-layout.module.css';

export const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${styles.noMargin} ${roboto.className}`}
        id="print-root"
      >
        {children}
      </body>
    </html>
  );
}
