import styles from './print-layout.module.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={styles.noMargin} id="print-root">
        {children}
      </body>
    </html>
  );
}
